export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS  = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL ="ADMIN_REGISTER_FAIL";

export const SELLER_LOGIN_FAIL = " SELLER_LOGIN_FAIL";
export const SELLER_LOGIN_REQUEST ="SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS ="SELLER_LOGIN_SUCCESS ";
export const SELLER_LOGOUT = "SELLER_LOGOUT";